---
name: Build Win cpp project

on:
  workflow_call:
  workflow_dispatch:

jobs:
  test_cpp_build:
    runs-on: windows-latest
    name: Build demo
    steps:
      - name: Checkout Files
        uses: actions/checkout@v4.1.4
      - name: Check Winget version
        shell: pwsh
        run: |
         Invoke-WebRequest -Uri https://github.com/microsoft/winget-cli/releases/download/v1.1.12653/Microsoft.DesktopAppInstaller_8wekyb3d8bbwe.msixbundle -OutFile C:\PS\WinGet.msixbundle
         Add-AppxPackage C:\WinGet.msixbundle
         winget --version
