---
name: Build project

on:
  workflow_call:

jobs:
  test_ccs_build:
    runs-on: ubuntu-latest
    name: Test palindrome project
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.4
