---
name: Build cpp project

on:
  workflow_call:
  workflow_dispatch:

jobs:
  test_cpp_build:
    runs-on: ubuntu-latest
    name: Build demo
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.4
        
      - name: build cmake
      - run: |
          mkdir cmake-demo
