---
name: Build Win cpp project

on:
  workflow_call:
  workflow_dispatch:

jobs:
  test_cpp_build:
    runs-on: windows-latest
    name: Build demo
    steps:
      - name: Checkout Files
        uses: actions/checkout@v4.1.4
      - name: Install cmake
        shell: pwsh
        run: |
         choco install cmake
         cmake --version
      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v2
      - name: Generate Cmake Configuration & Build 
        shell: pwsh
        run: |
          mkdir demo-build
          cd demo-build
          cmake .. 
          msbuild demo.sln
          
